services:
  postgres:
    image: postgres:latest
    container_name: igni_db
    environment:
      POSTGRES_USER: igni
      POSTGRES_PASSWORD: igni
      POSTGRES_DB: igni
    ports:
      - "5432:5432"
    volumes:
      # - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
# volumes:
#   postgres_data:
