services:
  postgres:
    image: postgres:latest
    container_name: igni_db
    environment:
      POSTGRES_USER: igni
      POSTGRES_PASSWORD: igni
      POSTGRES_DB: igni
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
  web:
    image: nginx
    container_name: igni_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - nginx_logs:/var/log/nginx
  igni:
    image: igni
    container_name: igni_app
    entrypoint: ["wait-for-it", "postgres:5432", "--", "/usr/local/bin/vidformer-igni", "server", "--config", "/etc/igni.toml"]
    environment:
      IGNI_DB: postgres://igni:igni@postgres:5432/igni
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./igni.toml:/etc/igni.toml
    depends_on:
      - postgres
volumes:
  postgres_data:
  nginx_logs:
