name: Publish

on:
  release:
    types: [published]

jobs:

  publish-py:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flit

    - name: Build and publish
      run: |
        pushd vidformer-py
        flit build
        flit publish
        popd
      env:
        FLIT_USERNAME: __token__
        FLIT_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

  publish-crate:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2
    - name: Deps
      run: bash ./scripts/deps.sh
    - name: Check Build
      run: cargo check
    - name: Publish
      run: cargo publish -p vidformer --token ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-docker:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: dominikwinecki/vidformer:latest,dominikwinecki/vidformer:${{ github.event.release.tag_name }}

  publish-binary:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2
    - name: Deps
      run: bash ./scripts/deps.sh
    - name: Check Build
      run: cargo check
    - name: Build release
      run: cargo build --release && cp ./target/release/vidformer-cli ./vidformer-cli-linux-amd64
    - name: Upload release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          vidformer-cli-linux-amd64