name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
    - name: Cache ffmpeg
      uses: actions/cache@v3
      with:
        path: |
          ./ffmpeg
        key: ${{ runner.os }}-ffmpeg-${{ hashFiles('**/deps_*.sh') }}
    - name: Deps
      run: bash ./scripts/deps_ci.sh
    - name: Download Test Video
      run: curl -O https://f.dominik.win/data/dve2/tos_720p.mp4 && curl -O https://f.dominik.win/data/dve2/apollo.jpg
    - name: Build Debug
      run: cargo build
    - name: Build Release
      run: cargo build --release
    - name: Run vidformer Rust tests
      run: cargo test --verbose
      timeout-minutes: 5
    - name: Install vidformer-py
      run: pip3 install ./vidformer-py
    - name: snake-pit pytest
      run: ./scripts/snake-pit.py
      timeout-minutes: 15
    - name: Valgrind Tests
      run: bash ./scripts/valgrind_test.sh
      timeout-minutes: 10

  system-ffmpeg-build:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: |
        sudo apt update && sudo apt upgrade -y && sudo apt install -y \
        autoconf \
        automake \
        build-essential \
        cmake \
        git-core \
        libass-dev \
        libfreetype6-dev \
        libgnutls28-dev \
        libsdl2-dev \
        libtool \
        libva-dev \
        libvdpau-dev \
        libvorbis-dev \
        libxcb1-dev \
        libxcb-shm0-dev \
        libxcb-xfixes0-dev \
        pkg-config \
        texinfo \
        wget \
        yasm \
        zlib1g-dev \
        nasm \
        libx264-dev \
        libx265-dev \
        libnuma-dev \
        libvpx-dev \
        libfdk-aac-dev \
        libmp3lame-dev \
        libopus-dev \
        libraw1394-dev \
        libdc1394-dev \
        libavc1394-dev \
        libiec61883-dev \
        libjack-dev \
        libfaad-dev \
        libgsm1-dev \
        libzmq3-dev \
        libssh-dev \
        libbluray-dev \
        libopenmpt-dev \
        ocl-icd-opencl-dev \
        libogg-dev \
        libspeex-dev \
        libtheora-dev \
        flite1-dev \
        libchromaprint-dev \
        libopenal-dev \
        libcdio-dev \
        libcaca-dev \
        libpocketsphinx-dev \
        libsphinxbase-dev \
        libbs2b-dev \
        liblilv-dev \
        libsratom-dev \
        libsord-dev \
        libserd-dev \
        librubberband-dev \
        libsamplerate0-dev \
        libmysofa-dev \
        libvidstab-dev \
        libzimg-dev \
        libgme-dev \
        librabbitmq-dev \
        libdav1d-dev \
        libzvbi-dev \
        libsnappy-dev \
        libaom-dev \
        libcodec2-dev \
        libshine-dev \
        libtwolame-dev \
        libwebp-dev \
        libxvidcore-dev \
        libsoxr-dev \
        libcdio-paranoia-dev \
        libcdio-cdda-dev \
        libsrt-gnutls-dev \
        libmfx-dev \
        libvorbis-dev \
        libavcodec-dev \
        libavdevice-dev \
        libavfilter-dev \
        libavformat-dev \
        libavutil-dev \
        libpostproc-dev \
        libswresample-dev \
        libswscale-dev \
        libopencv-dev \
        libclang-dev \
        clang \
        glslang-dev \
        libplacebo-dev \
        spirv-tools \
        libdvdnav-dev \
        libdvdread-dev \
        librist-dev \
        librsvg2-dev \
        libgdk-pixbuf2.0-dev \
        libcairo2-dev \
        libjxl-dev \
        libopenjp2-7-dev \
        librav1e-dev \
        libsvtav1-dev \
        libsvtav1enc-dev \
        libvpl-dev \
        curl \
        git
    - name: Install rust
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - name: Delete .cargo/config.toml
      run: rm -f .cargo/config.toml
    - name: Build
      run: cargo build
